//========================================================================
// SRAM RTL with custom low-level interface
//========================================================================
// This is the SRAM RTL model with our own low-level interface. It
// contains an instance of either a SRAM generated by the SRAM
// generator or a generic SRAM RTL model (SRAM_generic).
//
// The interface of this module are prefixed by port0_, meaning all reads
// and writes happen through the only port. Multiported SRAMs have ports
// prefixed by port1_, port2_, etc.
//
// The following list describes each port of this module.
//
//  Port Name     Direction  Description
//  ----------------------------------------------------------------------
//  port0_val     I          port enable (1 = enabled)
//  port0_type    I          transaction type, 0 = read, 1 = write
//  port0_idx     I          index of the SRAM
//  port0_wben    I          write byte enables
//  port0_wdata   I          write data
//  port0_rdata   O          read data output
//

`ifndef SRAM_SRAM_V
`define SRAM_SRAM_V

`include "sram/SRAM_generic.v"
`include "sram/SRAM_256x32_1rw.v"
`include "sram/SRAM_256x128_1rw.v"

// ''' TUTORIAL TASK '''''''''''''''''''''''''''''''''''''''''''''''''''''
// Include new SRAM configuration RTL model
// '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''\/

`include "sram/SRAM_128x32_1rw.v"

// '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''/\

module sram_SRAM
#(
  parameter p_num_entries = 256,
  parameter p_data_nbits  = 32,

  // Local constants not meant to be set from outside the module
  parameter c_addr_nbits  = $clog2(p_num_entries),
  parameter c_data_nbytes = (p_data_nbits+7)/8 // $ceil(p_data_nbits/8)
)(
  input  logic                        clk,
  input  logic                        reset,
  input  logic                        port0_val,
  input  logic                        port0_type,
  input  logic [c_addr_nbits-1:0]     port0_idx,
  input  logic [(p_data_nbits/8)-1:0] port0_wben,
  input  logic [p_data_nbits-1:0]     port0_wdata,
  output logic [p_data_nbits-1:0]     port0_rdata
);

  logic                        CLK; // clock
  logic                        CEN; // chip enable (active low)
  logic                        OEN; // output enable (active low)
  logic [c_addr_nbits-1:0]     A;   // address
  logic [(p_data_nbits/8)-1:0] WEN; // write byte enable (active low)
  logic [p_data_nbits-1:0]     D;   // write data
  logic [p_data_nbits-1:0]     Q;   // read data

  assign CLK = clk;
  assign CEN = ~port0_val;
  assign OEN = 0;
  assign A   = port0_idx;
  assign WEN = ( port0_type ) ? ~port0_wben : {(p_data_nbits/8){1'b1}};
  assign D   = port0_wdata;

  assign port0_rdata = Q;

  generate
    if      ( p_num_entries == 256 && p_data_nbits == 32  ) SRAM_256x32_1rw  sram (.*);
    else if ( p_num_entries == 256 && p_data_nbits == 128 ) SRAM_256x128_1rw sram (.*);

    // ''' TUTORIAL TASK '''''''''''''''''''''''''''''''''''''''''''''''''
    // Choose new SRAM configuration RTL model
    // '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''\/

    else if ( p_num_entries == 128 && p_data_nbits == 32 ) SRAM_128x32_1rw  sram (.*);

    // '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''/\

    else
      sram_SRAM_generic#(p_num_entries,p_data_nbits) sram (.*);

  endgenerate

endmodule

`endif /* SRAM_SRAM_V */

